# Generated by Django 5.0 on 2024-09-04 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organ_systems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organ_system", models.CharField(max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name="Organs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organ_name", models.CharField(max_length=29)),
                ("organ_function", models.CharField(max_length=100)),
                (
                    "organ_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organs.organ_systems",
                    ),
                ),
            ],
        ),
    ]
