# Generated by Django 5.0 on 2024-09-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organ_systems",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
