# Generated by Django 5.0 on 2024-09-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organs", "0003_alter_organs_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organs",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
