# Generated by Django 5.0 on 2024-09-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organs", "0004_alter_organs_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organ_systems",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
