# Generated by Django 5.0 on 2024-09-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organs", "0005_alter_organ_systems_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organs",
            name="organ_function",
            field=models.CharField(max_length=1000),
        ),
    ]
